services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - lab-07-templating:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d

  web:
    image: node:lts
    user: 'node'
    env_file: .env
    working_dir: /home/node/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./src:/home/node/app/src
    command: 'npm start'

volumes:
  lab-07-templating:

